server:
  port: 8082
spring:
  application:
    name: springcloud-consumer-news-feign
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true




