server:
  port: 8085


spring:
  application:
    name: springcloud-consumer-user-feign


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true