server:
  port: 8090


spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qilong666/microservice-config.git
          search-paths: /
          username: qilong666
          password: long931010
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
